// <auto-generated />
namespace JCarManager.DataAccess.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddTest4Column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTest4Column));
        
        string IMigrationMetadata.Id
        {
            get { return "201505141230222_AddTest4Column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
